/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.LineBorder;

/**
 *
 * @author lucad
 */
public class LoggedIndex extends javax.swing.JFrame {

     private ArrayList<String> Contacts;
     private ArrayList<JLabel> LContacts;
    /**
     * Creates new form LoggedIndex
     */
    public LoggedIndex() {
        initComponents();
        
        InitArrayList();
    }
    
    private void InitArrayList()
    {
        Contacts = new ArrayList<String>();
        LContacts = new ArrayList<JLabel>();
        for(int i = 0; i<5;i++)
        {
            Contacts.add("Contact"+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });
        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentShown
        // TODO add your handling code here:
        for(int i = 0; i<Contacts.size(); i++)
        {
            LContacts.add(new JLabel(Contacts.get(i)));
            LContacts.get(i).setComponentZOrder(jScrollPane1, i);
            LContacts.get(i).setVisible(true);
        }
    }//GEN-LAST:event_jScrollPane1ComponentShown

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        // TODO add your handling code here:
        for(int i = 0; i<Contacts.size(); i++)
        {
            LContacts.add(new JLabel(Contacts.get(i)));
            LContacts.get(i).setComponentZOrder(jScrollPane1, i);
            LContacts.get(i).setVisible(true);
        }
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JPanel p2 = new JPanel();
        p2.setLayout(new BoxLayout(p2, BoxLayout.PAGE_AXIS));
        p2.setBackground(Color.LIGHT_GRAY);
        //p2.setPreferredSize(new Dimension(70, 600));
        //p2.setAutoscrolls(true);
        jScrollPane1.setViewportView(p2);
        //JScrollPane scrollPane = new JScrollPane(p2);
//        scrollPane.setHorizontalScrollBarPolicy(
//                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        //jScrollPane1.setBounds(0, 0, 70, 800);
        for(int i = 0; i<Contacts.size(); i++)
        {
            //LContacts.add(new JLabel(Contacts.get(i)));
            
            
       
            LContacts.add(new JLabel(Contacts.get(i)));
            //sp1.setLayout(new FlowLayout());
            LContacts.get(i).setBackground(Color.WHITE);
            LContacts.get(i).setPreferredSize(new Dimension(70, 50));
            //LContacts.get(i).setBounds(0, 50*i, 100, 50);
            //LContacts.get(i).setMinimumSize(new Dimension(180,50));
            //LContacts.get(i).setMaximumSize(new Dimension(170, 50));
            LContacts.get(i).setBorder(new LineBorder(Color.RED));
            p2.add(LContacts.get(i));
            p2.add(Box.createRigidArea(new Dimension(0,5)));
//            try{
//            Thread.sleep(1000);
//            }
//            catch(Exception e)
//            {
//                e.printStackTrace();
//            }
            
//            LContacts.get(i).setComponentZOrder(jScrollPane1, i);
//            LContacts.get(i).setVisible(true);
        }
        JPanel spN = new JPanel();
        spN.setLayout(new FlowLayout());
        spN.setBackground(Color.WHITE);
        spN.setPreferredSize(new Dimension(70, 180));
        spN.setBounds(0,0,70,100);
        spN.setBorder(new LineBorder(Color.RED));
        p2.add(spN); 
    }//GEN-LAST:event_jButton1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
